name: mgrover-blog
channels:
  - conda-forge
  - pyviz
  - nodefaults
dependencies:
  - pip
  - ablog
  - cftime
  - colorspacious
  - jupyterlab>=3
  - myst-nb
  - pydata-sphinx-theme
  - python=3.11
  - cartopy
  - geopandas
  - fiona
  - siphon
  - geoviews
  - cmweather
  - hvplot
  - holoviews
  - matplotlib
  - sphinx
  - sphinx-autobuild
  - sphinx-comments
  - sphinx-panels
  - sphinxcontrib-bibtex
  - jupyterlab-myst
  - mystmd
  - feedgen
  - pyyaml
  - rich
  - sphinxext-opengraph
  - sphinx-design
  - pip:
    - sphinx-timeline
